---
all: # keys must be unique, i.e. only one 'hosts' per group
    hosts:
        master:
            ansible_host: 192.168.3.100
            ansible_user: slavko
    children:
        base_box:
            hosts:
                master:
        docker_box:
            hosts:
                master:
