apply-service-account:
	kubectl create -f traefik-service-account.yaml
destroy-service-account:
	kubectl delete -f traefik-service-account.yaml

apply-service-account-secret:
	kubectl create -f traefik-service-account-secret.yaml
destroy-service-account-secret:
	kubectl delete -f traefik-service-account-secret.yaml
